VirusTotal integration

```
<integration>
<name>virustotal</name>
<api_key>PASTE_YOUR_VT_API_KEY_HERE</api_key>
<rule_id>100200,100201</rule_id>
<alert_format>json</alert_format>
</integration>

```
add this to the integration block ``` sudo nano /var/ossec/etc/ossec.conf ```


 
Active Response

```
<command>
<name>remove-threat</name>
<executable>remove-threat.sh</executable>
</command>

```
This tells wazuh that the remove-threat.sh script is an available command.



```
<active-response>
<command>remove-threat</command>
<location>local</location>
<rules_id>87105</rules_id>
</active-response>

```      
This tells wazuh to trigger remove-threat when rule 87105 is generated